### ISSUE TITLE
Smoke gets harshly cut off by track.

### ISSUE THREAD

**Issue by CatCentralGitHub** [NotAika/AikaTweaks#2]
You could fix this by somehow making the bottom of the smoke fade away when it's touching the track.

**Comment by CatCentralGitHub** [comment]
Here, I'll provide an example

**Comment by CatCentralGitHub** [comment]
![image](https://user-images.githubusercontent.com/88316465/127837618-2db9f700-2057-49e1-9dcd-1de392836912.png)

**Comment by NotAika** [comment]
The issue is that the Quest lacks a properly working Depth Buffer, enabling it causes shader issues that I myself cannot fix. I've already tried to fix said issues with no luck, sorry :/

**Comment by CatCentralGitHub** [comment]
Can you at least keep searching for ways to fix it as a sort of side project?
